# permissions for end users to edit travellers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: traveller-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operators
    app.kubernetes.io/part-of: operators
    app.kubernetes.io/managed-by: kustomize
  name: traveller-editor-role
rules:
- apiGroups:
  - my.domain
  resources:
  - travellers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - my.domain
  resources:
  - travellers/status
  verbs:
  - get
